In [19]:
# multiple regression before and after PCA/LDA/Kernal PCA
# Took this code from prof's notebooks
# 
# i don't seem to be having any improvements after dimension reduction
# perhaps this can serve as a starting point if I'm doing something wrong..

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('processed.csv')

X = dataset.iloc[:,2:].values #We are not using column 1. Also we slice it this way because we want X to be a matrix
y = dataset.iloc[:,1].values

# print(y)

In [20]:
#Splitting the data into Training Set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

#Fitting Multiple Linear Regression to Training Set
from sklearn.linear_model import LinearRegression
mlrObj = LinearRegression()
mlrObj.fit(X_train,y_train)

#Predicting on the Test Set
y_pred = mlrObj.predict(X_test)

print(mlrObj.score(X_test,y_test))
print(y_test)
print(y_pred)

-41.343686607591614
[ 2190  7900 11490 ...  1150 28880  1100]
[ -3571.82412592 883451.62099183 -26574.32969532 ... -43033.77471145
 -61879.09648036  -1789.50428462]


In [21]:
#Applying PCA
from sklearn.decomposition import PCA
pcaObj = PCA(n_components=2)
X_train = pcaObj.fit_transform(X_train)
X_test = pcaObj.transform(X_test)
components_variance = pcaObj.explained_variance_ratio_

# regression on pca data
from sklearn.linear_model import LinearRegression
mlrObj = LinearRegression()
mlrObj.fit(X_train,y_train)

#Predicting on the Test Set
y_pred = mlrObj.predict(X_test)

print(mlrObj.score(X_test,y_test))
print(y_test)
print(y_pred)

-0.2972991745224134
[ 2190  7900 11490 ...  1150 28880  1100]
[ 16782.02291643   1595.68068229  34552.03028894 ... -10395.80116536
  15361.29197679   7963.82411305]


In [22]:
#Recreating train/test split after pca
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

#Applying LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
ldaObj = LDA(n_components=3)
X_train = ldaObj.fit_transform(X_train,y_train)
X_test = ldaObj.transform(X_test)
components_variance = ldaObj.explained_variance_ratio_

# regression on pca data
from sklearn.linear_model import LinearRegression
mlrObj = LinearRegression()
mlrObj.fit(X_train,y_train)

#Predicting on the Test Set
y_pred = mlrObj.predict(X_test)

print(mlrObj.score(X_test,y_test))
print(y_test)
print(y_pred)

-0.030778431756755875
[ 2190  7900 11490 ...  1150 28880  1100]
[22509.11777935 18665.94848518  8969.4742376  ... 21545.52120698
  7846.86343808 20860.66328994]


In [24]:
#Recreating train/test split after lda
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

#kernel PCA
from sklearn.decomposition import KernelPCA
kernelPCAObj = KernelPCA(n_components=2, kernel='rbf')
X_train = kernelPCAObj.fit_transform(X_train)  # caused memory error
X_test = kernelPCAObj.transform(X_test)

# regression on kernal pca data
from sklearn.linear_model import LinearRegression
mlrObj = LinearRegression()
mlrObj.fit(X_train,y_train)

#Predicting on the Test Set
y_pred = mlrObj.predict(X_test)

print(mlrObj.score(X_test,y_test))
print(y_test)
print(y_pred)

MemoryError: 