<a href="https://colab.research.google.com/github/nietzscholas9000/UsedCarsProject/blob/master/RegularizedRegresions_noBrands.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Poly w/o regularization

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('processed_without_modelbrand.csv')

X = dataset.iloc[:,2:].values 
y = dataset.iloc[:,1].values

#Splitting the data into Training Set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

#Fitting Multiple Linear Regression to Training Set
from sklearn.linear_model import LinearRegression
# mlrObj = LinearRegression()
# mlrObj.fit(X_train,y_train)



#Polynomial Regression No Regularization
from sklearn.preprocessing import PolynomialFeatures
polyFeatureObj = PolynomialFeatures(degree=3)
X_poly = polyFeatureObj.fit_transform(X_train)
X_poly_test = polyFeatureObj.fit_transform(X_test)  
prObj = LinearRegression()
prObj.fit(X_poly, y_train)
# runs out of memory above 3 degrees on normal colab

from sklearn.metrics import mean_squared_error
y_pred = enObj.predict(X_poly_test)
print(prObj.score(X_poly_test,y_test))
print(y_test)
print(y_pred)
print(mean_squared_error(y_test, y_pred))  # ran w/o this line
print(mean_squared_error(10**y_test, 10**y_pred))

0.8005625104685701
[3.11394335 4.0374265  3.91381385 ... 4.35216322 3.69853549 3.34242268]
[3.02619921 4.05935566 3.99195311 ... 4.08513394 3.71437823 3.22779485]
0.05737494051030482
891852291922635.6


In [10]:
# Ridge

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('processed_without_modelbrand.csv')

X = dataset.iloc[:,2:].values 
y = dataset.iloc[:,1].values

#Splitting the data into Training Set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)



#Polynomial Regression with Ridge
# runs out of memory above 3 degrees on normal colab
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
polyFeatureObj = PolynomialFeatures(degree=3)
X_poly = polyFeatureObj.fit_transform(X_train)
X_poly_test = polyFeatureObj.fit_transform(X_test) 
ridgeObj = Ridge()
ridgeObj.fit(X_poly, y_train)

from sklearn.metrics import mean_squared_error
y_pred = ridgeObj.predict(X_poly_test)
print(ridgeObj.score(X_poly_test,y_test))
print(y_test)
print(y_pred)
print(mean_squared_error(y_test, y_pred))
print(mean_squared_error(10**y_test, 10**y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=1.2489e-36): result may not be accurate.
  overwrite_a=True).T


0.8033358571627442
[3.11394335 4.0374265  3.91381385 ... 4.35216322 3.69853549 3.34242268]
[3.01442804 4.07314428 3.98264876 ... 4.08748082 3.71545887 3.2213238 ]
0.04965209669429757
66301784.96782527


In [11]:
# Lasso

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('processed_without_modelbrand.csv')

X = dataset.iloc[:,2:].values 
y = dataset.iloc[:,1].values

#Splitting the data into Training Set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)


#Polynomial Regression with Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Lasso
polyFeatureObj = PolynomialFeatures(degree=3)
X_poly = polyFeatureObj.fit_transform(X_train)
X_poly_test = polyFeatureObj.fit_transform(X_test)  
lassoObj = Lasso()
lassoObj.fit(X_poly, y_train)

from sklearn.metrics import mean_squared_error
y_pred = lassoObj.predict(X_poly_test)
print(lassoObj.score(X_poly_test,y_test))
print(y_test)
print(y_pred)
print(mean_squared_error(y_test, y_pred))
print(mean_squared_error(10**y_test, 10**y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 6393.461759487065, tolerance: 5.617437698763439
  positive)


0.7727468879054702
[3.11394335 4.0374265  3.91381385 ... 4.35216322 3.69853549 3.34242268]
[3.02619921 4.05935566 3.99195311 ... 4.08513394 3.71437823 3.22779485]
0.05737494051030482
891852291922635.6


In [12]:
# ElasticNet

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('processed_without_modelbrand.csv')

X = dataset.iloc[:,2:].values 
y = dataset.iloc[:,1].values

#Splitting the data into Training Set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)


#Polynomial Regression with ElasticNet
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import ElasticNet
polyFeatureObj = PolynomialFeatures(degree=3)
X_poly = polyFeatureObj.fit_transform(X_train)
X_poly_test = polyFeatureObj.fit_transform(X_test)  
enObj = ElasticNet(l1_ratio=1)
enObj.fit(X_poly, y_train)

from sklearn.metrics import mean_squared_error
print(enObj.score(X_poly_test,y_test))
y_pred = enObj.predict(X_poly_test)
print(y_test)
print(y_pred)
print(mean_squared_error(y_test, y_pred))
print(mean_squared_error(10**y_test, 10**y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 6393.461759487065, tolerance: 5.617437698763439
  positive)


0.7727468879054702
[3.11394335 4.0374265  3.91381385 ... 4.35216322 3.69853549 3.34242268]
[3.02619921 4.05935566 3.99195311 ... 4.08513394 3.71437823 3.22779485]
0.05737494051030482
891852291922635.6


In [0]:
#Predicting on the Test Set
print(prObj.score(X_poly_test,y_test))
y_pred = prObj.predict(X_poly_test)
print(y_pred)
print(y_test)


# calculating mean squared error from of the models
MSE = np.mean((y_test - y_pred)**2)
MSE_sig = np.mean((y_test - y_sig_pred)**2)